Fix NoSuchMethodError in VerifyMojo (#114)
Since d004535b103d884b8acbc8d574d1ebe57b9e3c94 execution fails with

    [ERROR] Failed to execute goal io.gatling:gatling-maven-plugin:4.2.5:verify (default) on project perftest: Execution default of goal io.gatling:gatling-maven-plugin:4.2.5:verify failed: An API incompatibility was encountered while executing io.gatling:gatling-maven-plugin:4.2.5:verify: java.lang.NoSuchMethodError: 'boolean org.codehaus.plexus.util.StringUtils.contains(java.lang.String, java.lang.String)'

because plexus utils are no longer available to the mojo.

Signed-off-by: Harald Albers <github@albersweb.de>

Signed-off-by: Harald Albers <github@albersweb.de>